var hierarchy =
[
    [ "TransferAccountInfo.Account", "classcom_1_1toast_1_1android_1_1gamebase_1_1auth_1_1transfer_1_1data_1_1_transfer_account_info_1_1_account.html", null ],
    [ "Gamebase.Analytics", "classcom_1_1toast_1_1android_1_1gamebase_1_1_gamebase_1_1_analytics.html", null ],
    [ "AuthProvider", "interfacecom_1_1toast_1_1android_1_1gamebase_1_1base_1_1auth_1_1_auth_provider.html", null ],
    [ "AuthProviderProfile", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1auth_1_1_auth_provider_profile.html", null ],
    [ "GamebaseWebViewConfiguration.Builder", "classcom_1_1toast_1_1android_1_1gamebase_1_1_gamebase_web_view_configuration_1_1_builder.html", null ],
    [ "GamebaseConfiguration.Builder", "classcom_1_1toast_1_1android_1_1gamebase_1_1_gamebase_configuration_1_1_builder.html", null ],
    [ "TransferAccountInfo.Condition", "classcom_1_1toast_1_1android_1_1gamebase_1_1auth_1_1transfer_1_1data_1_1_transfer_account_info_1_1_condition.html", null ],
    [ "Gamebase.Contact", "classcom_1_1toast_1_1android_1_1gamebase_1_1_gamebase_1_1_contact.html", null ],
    [ "Gamebase", "classcom_1_1toast_1_1android_1_1gamebase_1_1_gamebase.html", null ],
    [ "GamebaseCallback", "interfacecom_1_1toast_1_1android_1_1gamebase_1_1_gamebase_callback.html", null ],
    [ "GamebaseDataCallback< T >", "interfacecom_1_1toast_1_1android_1_1gamebase_1_1_gamebase_data_callback.html", null ],
    [ "GamebaseError", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1_gamebase_error.html", null ],
    [ "GamebaseSystemInfo", "classcom_1_1toast_1_1android_1_1gamebase_1_1_gamebase_system_info.html", null ],
    [ "GamebaseWebViewConfiguration", "classcom_1_1toast_1_1android_1_1gamebase_1_1_gamebase_web_view_configuration.html", null ],
    [ "GamebaseWebViewStyle", "classcom_1_1toast_1_1android_1_1gamebase_1_1_gamebase_web_view_style.html", null ],
    [ "Gamebase.Launching", "classcom_1_1toast_1_1android_1_1gamebase_1_1_gamebase_1_1_launching.html", null ],
    [ "LaunchingMaintenanceInfo", "classcom_1_1toast_1_1android_1_1gamebase_1_1launching_1_1data_1_1_launching_maintenance_info.html", null ],
    [ "LaunchingNoticeInfo", "classcom_1_1toast_1_1android_1_1gamebase_1_1launching_1_1data_1_1_launching_notice_info.html", null ],
    [ "LaunchingStatusUpdateListener", "interfacecom_1_1toast_1_1android_1_1gamebase_1_1launching_1_1listeners_1_1_launching_status_update_listener.html", null ],
    [ "Loggable", "interfacecom_1_1toast_1_1android_1_1gamebase_1_1base_1_1log_1_1_loggable.html", null ],
    [ "Logger", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1log_1_1_logger.html", null ],
    [ "Gamebase.Logger", "classcom_1_1toast_1_1android_1_1gamebase_1_1_gamebase_1_1_logger.html", null ],
    [ "AuthProvider.LoginCallback", "interfacecom_1_1toast_1_1android_1_1gamebase_1_1base_1_1auth_1_1_auth_provider_1_1_login_callback.html", null ],
    [ "AuthProvider.LogoutCallback", "interfacecom_1_1toast_1_1android_1_1gamebase_1_1base_1_1auth_1_1_auth_provider_1_1_logout_callback.html", null ],
    [ "Gamebase.Network", "classcom_1_1toast_1_1android_1_1gamebase_1_1_gamebase_1_1_network.html", null ],
    [ "Observer", "interfacecom_1_1toast_1_1android_1_1gamebase_1_1observer_1_1_observer.html", null ],
    [ "ObserverMessage", "classcom_1_1toast_1_1android_1_1gamebase_1_1observer_1_1_observer_message.html", null ],
    [ "NetworkManager.OnChangedStatusListener", "interfacecom_1_1toast_1_1android_1_1gamebase_1_1base_1_1_network_manager_1_1_on_changed_status_listener.html", null ],
    [ "SimpleInputTextDialog.OnClickListener", "interfacecom_1_1toast_1_1android_1_1gamebase_1_1base_1_1ui_1_1_simple_input_text_dialog_1_1_on_click_listener.html", null ],
    [ "Gamebase.Purchase", "classcom_1_1toast_1_1android_1_1gamebase_1_1_gamebase_1_1_purchase.html", null ],
    [ "PurchaseProvider", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1purchase_1_1_purchase_provider.html", null ],
    [ "Gamebase.Push", "classcom_1_1toast_1_1android_1_1gamebase_1_1_gamebase_1_1_push.html", null ],
    [ "PushProvider", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1push_1_1_push_provider.html", null ],
    [ "RenewalModeType", "enumcom_1_1toast_1_1android_1_1gamebase_1_1auth_1_1transfer_1_1data_1_1_renewal_mode_type.html", null ],
    [ "RenewalTargetType", "enumcom_1_1toast_1_1android_1_1gamebase_1_1auth_1_1transfer_1_1data_1_1_renewal_target_type.html", null ],
    [ "RuntimeException", null, [
      [ "GamebaseException", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1_gamebase_exception.html", null ]
    ] ],
    [ "ScreenOrientation", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1_screen_orientation.html", null ],
    [ "ServerPushEvent", "interfacecom_1_1toast_1_1android_1_1gamebase_1_1serverpush_1_1_server_push_event.html", null ],
    [ "ServerPushEventMessage", "classcom_1_1toast_1_1android_1_1gamebase_1_1serverpush_1_1_server_push_event_message.html", null ],
    [ "SimpleAlertDialog", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1ui_1_1_simple_alert_dialog.html", null ],
    [ "SimpleInputTextDialog", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1ui_1_1_simple_input_text_dialog.html", null ],
    [ "SimpleMultiChoiceDialog", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1ui_1_1_simple_multi_choice_dialog.html", null ],
    [ "SimpleSelectItemDialog", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1ui_1_1_simple_select_item_dialog.html", null ],
    [ "SimpleToast", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1ui_1_1_simple_toast.html", null ],
    [ "PurchaseProvider.StoreCode", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1purchase_1_1_purchase_provider_1_1_store_code.html", null ],
    [ "LaunchingInfo.TcProductType", "interfacecom_1_1toast_1_1android_1_1gamebase_1_1launching_1_1data_1_1_launching_info_1_1_tc_product_type.html", null ],
    [ "ToastDuration", "interfacecom_1_1toast_1_1android_1_1gamebase_1_1base_1_1annotation_1_1_toast_duration.html", null ],
    [ "ObserverMessage.Type", "classcom_1_1toast_1_1android_1_1gamebase_1_1observer_1_1_observer_message_1_1_type.html", null ],
    [ "ServerPushEventMessage.Type", "classcom_1_1toast_1_1android_1_1gamebase_1_1serverpush_1_1_server_push_event_message_1_1_type.html", null ],
    [ "PushProvider.Type", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1push_1_1_push_provider_1_1_type.html", null ],
    [ "Gamebase.Util", "classcom_1_1toast_1_1android_1_1gamebase_1_1_gamebase_1_1_util.html", null ],
    [ "ValueObject", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1_value_object.html", [
      [ "AuthGamebaseToken", "classcom_1_1toast_1_1android_1_1gamebase_1_1auth_1_1data_1_1_auth_gamebase_token.html", null ],
      [ "AuthMappingInfo", "classcom_1_1toast_1_1android_1_1gamebase_1_1auth_1_1data_1_1_auth_mapping_info.html", null ],
      [ "AuthToken", "classcom_1_1toast_1_1android_1_1gamebase_1_1auth_1_1data_1_1_auth_token.html", null ],
      [ "BanInfo", "classcom_1_1toast_1_1android_1_1gamebase_1_1auth_1_1data_1_1_ban_info.html", null ],
      [ "ForcingMappingTicket", "classcom_1_1toast_1_1android_1_1gamebase_1_1auth_1_1mapping_1_1data_1_1_forcing_mapping_ticket.html", null ],
      [ "TransferAccountFailInfo", "classcom_1_1toast_1_1android_1_1gamebase_1_1auth_1_1transfer_1_1data_1_1_transfer_account_fail_info.html", null ],
      [ "TransferAccountInfo", "classcom_1_1toast_1_1android_1_1gamebase_1_1auth_1_1transfer_1_1data_1_1_transfer_account_info.html", null ],
      [ "TransferAccountRenewConfiguration", "classcom_1_1toast_1_1android_1_1gamebase_1_1auth_1_1transfer_1_1data_1_1_transfer_account_renew_configuration.html", null ],
      [ "PurchasableItem", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1purchase_1_1_purchasable_item.html", null ],
      [ "PurchasableReceipt", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1purchase_1_1_purchasable_receipt.html", null ],
      [ "PurchasableRetryTransactionResult", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1purchase_1_1_purchasable_retry_transaction_result.html", null ],
      [ "PushConfiguration", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1push_1_1_push_configuration.html", null ],
      [ "GamebaseConfiguration", "classcom_1_1toast_1_1android_1_1gamebase_1_1_gamebase_configuration.html", null ],
      [ "LaunchingInfo", "classcom_1_1toast_1_1android_1_1gamebase_1_1launching_1_1data_1_1_launching_info.html", null ],
      [ "LaunchingStatus", "classcom_1_1toast_1_1android_1_1gamebase_1_1launching_1_1data_1_1_launching_status.html", null ]
    ] ],
    [ "Gamebase.WebView", "classcom_1_1toast_1_1android_1_1gamebase_1_1_gamebase_1_1_web_view.html", null ],
    [ "AuthProvider.WithdrawCallback", "interfacecom_1_1toast_1_1android_1_1gamebase_1_1base_1_1auth_1_1_auth_provider_1_1_withdraw_callback.html", null ],
    [ "BroadcastReceiver", null, [
      [ "NetworkManager", "classcom_1_1toast_1_1android_1_1gamebase_1_1base_1_1_network_manager.html", null ]
    ] ]
];